defmodule GenServerIo.Anagrams.WordLists do
  @moduledoc """
  Provides word lists for different languages and length categories.
  """

  @english_short [
    "CREATING",
    "REACTION",
    "TRIANGLE",
    "ABSOLUTE",
    "COMPLETE",
    "QUESTION",
    "PRACTICE",
    "KEYBOARD",
    "STANDARD",
    "DIRECTOR",
    "PROTEINS",
    "ROUTINES",
    "TERMINAL",
    "ATIONAL",
    "CHAPTERS",
    "IMENTOS",
    "ACIONES",
    "RELATION",
    "MATERIAL",
    "ORIENTAL",
    "PAINTERS",
    "CONTAINS",
    "RESTRAIN",
    "CRASHING",
    "BREAKING",
    "LIGHTING",
    "PAINTERS",
    "FLOATING",
    "CREATION",
    "ORGANIST",
    "COASTLINE",
    "SECTIONAL",
    "TRIANGLES",
    "NIGHTMARE",
    "ORDINATES",
    "ALMONRIES",
    "RATIONALE",
    "SECTARIAN",
    "CAUTIONER",
    "IONARIES",
    "CONTRAILS",
    "NOSTALGIC",
    "SECTIONAL",
    "RATIONALES",
    "SECTORIAL",
    "COLANDERS",
    "ORDINATES",
    "INTRODUCE",
    "REDUCTION",
    "CUSTODIAN"
  ]

  @english_medium [
    "PERSONALITY",
    "GENERATIONS",
    "TEMPERATURE",
    "COMFORTABLE",
    "OBSERVATION",
    "DEMONSTRATE",
    "CELEBRATION",
    "EDUCATIONAL",
    "PHOTOGRAPHY",
    "ALTERNATIVE",
    "COUNTRYSIDE",
    "INSTRUMENTS",
    "OPERATIONAL",
    "PRESIDENTIAL",
    "GENERATIONS",
    "COORDINATES",
    "ATMOSPHERIC",
    "COUNTRYSIDE",
    "INSTRUMENTS",
    "THEORETICAL",
    "PERSONALITY",
    "RESIDENTIAL",
    "CREDENTIALS",
    "ALLEGATIONS",
    "INCORPORATE",
    "DECLARATION",
    "CORRELATION",
    "OPERATIONAL",
    "DEVASTATING",
    "CHRISTOPHER",
    "DEMONSTRATE",
    "QUESTIONING",
    "COMFORTABLE",
    "TEMPERATURE",
    "OBSERVATION",
    "PERSONALITY",
    "GENERATIONS",
    "CELEBRATION",
    "OPERATIONAL",
    "DOCUMENTARY",
    "COUNTRYSIDE",
    "INSTRUMENTS",
    "COORDINATES",
    "ATMOSPHERIC",
    "THEORETICAL",
    "RESIDENTIAL",
    "CREDENTIALS",
    "ALLEGATIONS",
    "INCORPORATE",
    "DECLARATION"
  ]

  @english_long [
    "REPRESENTATION",
    "CHARACTERISTIC",
    "RESPONSIBILITY",
    "IMPLEMENTATION",
    "TRANSFORMATION",
    "EXTRAORDINARY",
    "ADMINISTRATOR",
    "CONGRATULATIONS",
    "UNFORTUNATELY",
    "MULTIPLICATION",
    "CONSIDERATIONS",
    "DISCRIMINATION",
    "REPRESENTATIVE",
    "TRANSPORTATION",
    "INFRASTRUCTURE",
    "INTERPRETATION",
    "DEMONSTRATIONS",
    "CONTROVERSIAL",
    "REVOLUTIONARY",
    "DETERMINATION",
    "CORRESPONDENCE",
    "UNDERSTANDING",
    "ENVIRONMENTAL",
    "INTERNATIONAL",
    "ORGANIZATIONS",
    "PROFESSIONALS",
    "DISTINGUISHED",
    "RELATIONSHIPS",
    "CONTRIBUTIONS",
    "APPROXIMATELY",
    "DISADVANTAGES",
    "CIRCUMSTANCES",
    "ESTABLISHMENT",
    "CONCENTRATION",
    "PERSONALITIES",
    "OPPORTUNITIES",
    "COMPREHENSIVE",
    "ALTERNATIVELY",
    "EXTRAORDINARY",
    "SOPHISTICATED",
    "MANUFACTURING",
    "CONFIGURATION",
    "DOCUMENTATION",
    "SPECIFICATION",
    "AUTHORIZATION",
    "COLLABORATION",
    "CERTIFICATION",
    "INVESTIGATION",
    "COMMUNICATION",
    "ENTERTAINMENT",
    "ADMINISTRATOR"
  ]

  @russian_short [
    "СОЗДАНИЕ",
    "РЕАКЦИЯ",
    "ПРАКТИКА",
    "СТАНДАРТ",
    "ДИРЕКТОР",
    "КЛАВИАТУРА",
    "ТРЕУГОЛЬНИК",
    "ВОПРОС",
    "МАТЕРИАЛ",
    "ОПЕРАЦИЯ",
    "КОНТРОЛЬ",
    "ПРИНЦИП",
    "КРИТЕРИЙ",
    "СТРУКТУРА",
    "КУЛЬТУРА",
    "ПОЛИТИКА",
    "ТРАДИЦИЯ",
    "КАТЕГОРИЯ",
    "ТЕХНИКА",
    "МЕХАНИЗМ",
    "ДОКТРИНА",
    "КОНЦЕПЦИЯ",
    "КРИТИКА",
    "ПРАКТИКУМ",
    "ПРОБЛЕМА",
    "ПРОГРАММА",
    "СИСТЕМА",
    "ПРОЦЕСС",
    "РЕЗУЛЬТАТ",
    "ХАРАКТЕР",
    "ТЕРРИТОРИЯ",
    "ЛИТЕРАТУРА",
    "АРХИТЕКТУРА",
    "ДИРЕКТИВА",
    "КОНСТРУКЦИЯ",
    "РАЦИОНАЛЬ",
    "ОПЕРАЦИОНАЛ",
    "СТРАТЕГИЯ",
    "ЭМОЦИЯ",
    "РЕВОЛЮЦИЯ",
    "ЭВОЛЮЦИЯ",
    "ИННОВАЦИЯ",
    "МОТИВАЦИЯ",
    "ИНТЕГРАЦИЯ",
    "КООРДИНАЦИЯ",
    "КОРРЕЛЯЦИЯ",
    "КОЛЛЕКЦИЯ",
    "ИНФЕКЦИЯ"
  ]

  @russian_medium [
    "ТЕМПЕРАТУРА",
    "НАБЛЮДЕНИЕ",
    "ДЕМОНСТРАЦИЯ",
    "ОБРАЗОВАНИЕ",
    "ФОТОГРАФИЯ",
    "АЛЬТЕРНАТИВА",
    "ПРАЗДНОВАТЬ",
    "КОМФОРТАБЕЛЬНЫЙ",
    "ОРГАНИЗАЦИЯ",
    "ИНФОРМАЦИЯ",
    "КОММУНИКАЦИЯ",
    "КООРДИНАЦИЯ",
    "КОРПОРАЦИЯ",
    "ОПЕРАЦИОННЫЙ",
    "КОНСТИТУЦИЯ",
    "КОНСУЛЬТАЦИЯ",
    "КОНФИГУРАЦИЯ",
    "КОРРЕЛЯЦИЯ",
    "КООПЕРАЦИЯ",
    "КООРДИНАТОР",
    "ДОКУМЕНТАЦИЯ",
    "ДЕМОКРАТИЯ",
    "ДЕКЛАРАЦИЯ",
    "ДЕГРАДАЦИЯ",
    "ДЕЛЕГАЦИЯ",
    "ДЕМОНТАЖ",
    "ДЕПАРТАМЕНТ",
    "ДЕСТАБИЛИЗАЦИЯ",
    "ДИСКРИМИНАЦИЯ",
    "ДЕКОМПОЗИЦИЯ",
    "ГЕНЕРАЦИЯ",
    "ГАРМОНИЗАЦИЯ",
    "ГЛОБАЛИЗАЦИЯ",
    "ГРАДАЦИЯ",
    "ИДЕАЛИЗАЦИЯ",
    "ИДЕНТИФИКАЦИЯ",
    "ИЛЛЮСТРАЦИЯ",
    "ИМИТАЦИЯ",
    "ИММИГРАЦИЯ",
    "ИМПЛИКАЦИЯ",
    "ИМПРОВИЗАЦИЯ",
    "ИНИЦИАТИВА",
    "ИНСПЕКЦИЯ",
    "ИНСТАЛЛЯЦИЯ",
    "ИНТЕРПРЕТАЦИЯ",
    "ИНТОНАЦИЯ",
    "ИНДИКАЦИЯ",
    "ИРРАДИАЦИЯ"
  ]

  @russian_long [
    "ПРЕДСТАВИТЕЛЬСТВО",
    "ХАРАКТЕРИСТИКА",
    "ОТВЕТСТВЕННОСТЬ",
    "ТРАНСФОРМАЦИЯ",
    "АДМИНИСТРАТОР",
    "ПОЗДРАВЛЕНИЯ",
    "УМНОЖЕНИЕ",
    "ПЕРЕОРИЕНТАЦИЯ",
    "ПЕРСОНАЛИЗАЦИЯ",
    "ПРОФЕССИОНАЛИЗМ",
    "ПРОТИВОРЕЧИЕ",
    "ПРОИЗВОДИТЕЛЬНОСТЬ",
    "ПРОГНОЗИРОВАНИЕ",
    "ПРОВОКАЦИЯ",
    "ПРОЛИФЕРАЦИЯ",
    "РАДИОАКТИВНОСТЬ",
    "РАСПРЕДЕЛЕНИЕ",
    "РЕАБИЛИТАЦИЯ",
    "РЕАЛИЗАЦИЯ",
    "РЕАНИМАЦИЯ",
    "РЕКОНСТРУКЦИЯ",
    "РЕКОМЕНДАЦИЯ",
    "РЕПРЕЗЕНТАЦИЯ",
    "РЕСПУБЛИКАНСКИЙ",
    "РЕСТАВРАЦИЯ",
    "РЕТРОСПЕКТИВА",
    "СЕКУЛЯРИЗАЦИЯ",
    "СЕНСАЦИОННЫЙ",
    "СИСТЕМАТИЗАЦИЯ",
    "СОЦИАЛИЗАЦИЯ",
    "СПЕЦИАЛИЗАЦИЯ",
    "СПЕЦИФИКАЦИЯ",
    "СТАБИЛИЗАЦИЯ",
    "СТАНДАРТИЗАЦИЯ",
    "СТЕРИЛИЗАЦИЯ",
    "СТРАТИФИКАЦИЯ",
    "СТРУКТУРАЛИЗМ",
    "СУБОРДИНАЦИЯ",
    "ТЕРРИТОРИАЛЬНОСТЬ",
    "ТЕХНОЛОГИЧЕСКИЙ",
    "ТОЛЕРАНТНОСТЬ",
    "ТРАДИЦИОННЫЙ",
    "ТРАНСЛИТЕРАЦИЯ",
    "ТРАНСПОРТИРОВКА",
    "УНИФИКАЦИЯ",
    "УНИВЕРСАЛИЗАЦИЯ",
    "УРБАНИЗАЦИЯ",
    "ФАЛЬСИФИКАЦИЯ",
    "ФОРМАЛИЗАЦИЯ"
  ]

  @doc """
  Gets a random base word for the given language and length category.
  Excludes words that have already been used.
  If all words have been used, resets and returns a random word from the full list.
  """
  def random_word(language, category, used_words \\ MapSet.new()) do
    words = get_word_list(language, category)
    available_words = Enum.reject(words, fn word -> MapSet.member?(used_words, word) end)

    case available_words do
      [] ->
        # All words used, pick from full list (game will reset used_words)
        Enum.random(words)

      available ->
        Enum.random(available)
    end
  end

  @doc """
  Gets the word list for the given language and category.
  """
  def get_word_list(:en, :short), do: @english_short
  def get_word_list(:en, :medium), do: @english_medium
  def get_word_list(:en, :long), do: @english_long
  def get_word_list(:ru, :short), do: @russian_short
  def get_word_list(:ru, :medium), do: @russian_medium
  def get_word_list(:ru, :long), do: @russian_long
end
